name: Base Workflow
description: Reusable base workflow

inputs:
  go-version:
    description: Go version to use
    required: true

runs:
  using: composite
  steps:
    - name: Run MarkdownLint
      uses: DavidAnson/markdownlint-cli2-action@v18
      with:
        globs: "**/*.md"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install dependencies
      shell: bash
      run: make tools

    - name: Check
      shell: bash
      run: make check
